# Generated by Django 4.2.8 on 2024-02-29 15:34
from django_summernote.fields import SummernoteTextField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0002_subscriptionplan_sku'),
        ('profiles', '0003_rename_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('content', SummernoteTextField()),
                ('short_description', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_insights', to='profiles.userprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='subscription.subscriptionplan')),
            ],
        ),
    ]
