# Generated by Django 4.2.8 on 2024-02-29 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0002_insight_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
