# Generated by Django 4.2.8 on 2024-02-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0003_alter_insight_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='insights_cover_images/'),
        ),
    ]
