# Generated by Django 4.2.8 on 2024-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0004_insight_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='display',
            field=models.CharField(choices=[('TXT', 'Text'), ('IMG', 'Image')], default='IMG', max_length=3),
        ),
    ]
