# Generated by Django 4.2.8 on 2024-03-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0006_alter_insight_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
