# Generated by Django 4.2.8 on 2024-03-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0009_alter_insight_slug_alter_insight_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
