# Generated by Django 4.2.8 on 2024-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0011_alter_insight_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=models.TextField(),
        ),
    ]
