# Generated by Django 4.2.8 on 2024-03-18 18:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_insights', '0012_alter_insight_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=models.TextField()
        ),
    ]
