# Generated by Django 4.2.8 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
