# Generated by Django 4.2.8 on 2024-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='staged',
            field=models.BooleanField(default=False),
        ),
    ]
