# Generated by Django 4.2.8 on 2024-03-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_stripe_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='sku',
        ),
    ]
