# Generated by Django 4.2.8 on 2024-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_subscriptionplan_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='stripe_plan_id',
            new_name='stripe_price_id',
        ),
    ]
