# Generated by Django 4.2.8 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmetrics',
            name='renewed_subscriptions',
            field=models.IntegerField(default=0),
        ),
    ]
