# Generated by Django 4.2.8 on 2024-03-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_metrics', '0002_financialmetrics_renewed_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialmetrics',
            name='plan_metrics',
        ),
        migrations.DeleteModel(
            name='PlanMetrics',
        ),
    ]
