# Generated by Django 4.2.8 on 2024-03-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_metrics', '0003_remove_financialmetrics_plan_metrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmetrics',
            old_name='canceled_subscription_revenue',
            new_name='monthly_revenue',
        ),
        migrations.RemoveField(
            model_name='financialmetrics',
            name='monthly_recurring_revenue',
        ),
        migrations.RemoveField(
            model_name='financialmetrics',
            name='new_subscription_revenue',
        ),
        migrations.RemoveField(
            model_name='financialmetrics',
            name='total_revenue',
        ),
    ]
