# Generated by Django 4.2.8 on 2024-01-05 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_activesubscription_remove_orderlineitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
