# Generated by Django 4.2.8 on 2024-03-12 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_activesubscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesubscription',
            name='purchase_number',
        ),
        migrations.AddField(
            model_name='activesubscription',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activesubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
