# Generated by Django 4.2.8 on 2024-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_activesubscription_purchase_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesubscription',
            old_name='end_date',
            new_name='renewal_date',
        ),
    ]
