# Generated by Django 4.2.8 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_end_date_activesubscription_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activesubscription',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
