# Generated by Django 4.2.8 on 2024-03-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_activesubscription_current_period_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesubscription',
            old_name='end_date',
            new_name='canceled_at',
        ),
    ]
